#!/usr/bin/env zsh

# Setting up STOW_FOLDERS and DOTFILES variables
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# Stowing dotfiles
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd


