#!/usr/bin/env bash

# Setting up STOW_FOLDERS and DOTFILES variables
if [ -z "$STOW_FOLDERS" ]; then
    STOW_FOLDERS="bin zsh aliases i3 tmux nvim"
fi

if [ -z "$DOTFILES" ]; then
    DOTFILES="$HOME/.dotfiles"
fi

# Stowing dotfiles
pushd "$DOTFILES" > /dev/null
IFS=' ' read -ra FOLDERS <<< "$STOW_FOLDERS"
for folder in "${FOLDERS[@]}"; do
    echo "stow $folder"
    stow -D "$folder"
    stow "$folder"
done
popd > /dev/null
