#!/bin/sh

# Setting up STOW_FOLDERS and DOTFILES variables
if [ -z "$STOW_FOLDERS" ]; then
    STOW_FOLDERS="i3 nvim scripts starship tmux zsh picom polybar"
fi

if [ -z "$DOTFILES" ]; then
    DOTFILES="$HOME/.dotfiles"
fi

pushd "$DOTFILES" > /dev/null
IFS=' ' read -ra FOLDERS <<< "$STOW_FOLDERS"
for folder in "${FOLDERS[@]}"; do
    echo "Removing $folder"
    stow -D "$folder"
done
popd > /dev/null
