require("user.launch")
require("user.options")
require("user.keymaps")

-- themes
spec("user.plugins.themes.catppuccino")
spec("user.plugins.themes.darkplus")
spec("user.plugins.themes.tokyonight")
spec("user.plugins.themes.onedark")
spec("user.plugins.themes.github")

-- plugins
spec("user.plugins.devicons")
spec("user.plugins.treesitter")
spec("user.plugins.whichkey")
spec("user.plugins.mason")
spec("user.plugins.lspconfig")
spec("user.plugins.none-ls")
spec("user.plugins.conform")
spec("user.plugins.cmp")
spec("user.plugins.telescope")
spec("user.plugins.nvimtree")
-- spec("user.plugins.trouble")
-- spec("user.plugins.oil")
spec("user.plugins.comment")
spec("user.plugins.lualine")
spec("user.plugins.navic")
spec("user.plugins.breadcrumbs")
spec("user.plugins.illuminate")
spec("user.plugins.indentline")
spec("user.plugins.schemastore")
spec("user.plugins.tmux-navigator")
spec("user.plugins.spectre")
spec("user.plugins.autopairs")
spec("user.plugins.dap")
spec("user.plugins.dap-ui")
spec("user.plugins.avante")

-- extras
spec("user.plugins.extras.noice")
spec("user.plugins.extras.copilot")
spec("user.plugins.extras.copilot-chat")
spec("user.plugins.extras.harpoon")
spec("user.plugins.extras.fold")
spec("user.plugins.extras.visual-multi")
spec("user.plugins.extras.surround")
spec("user.plugins.extras.rainbow")
spec("user.plugins.extras.lazygit")
spec("user.plugins.extras.eyeliner")
spec("user.plugins.extras.neotab")
spec("user.plugins.extras.diffview")
spec("user.plugins.extras.lab")
spec("user.plugins.extras.drop")
spec("user.plugins.extras.obsidian")
spec("user.plugins.extras.markdown-preview")
spec("user.plugins.extras.react-extract")
spec("user.plugins.extras.autosave")
spec("user.plugins.extras.virtualtext")
spec("user.plugins.extras.colorizer")
-- spec("user.plugins.extras.dap-python")
-- spec("user.plugins.extras.qml")
-- spec("user.plugins.extras.neoscroll")

-- lazy
require("user.lazy")
