require("user.launch")
require("user.options")
require("user.keymaps")

spec("user.plugins.colorscheme")
spec("user.plugins.devicons")
spec("user.plugins.treesitter")
spec("user.plugins.whichkey")
spec("user.plugins.mason")
spec("user.plugins.lspconfig")
spec("user.plugins.none-ls")
spec("user.plugins.conform")
spec("user.plugins.cmp")
spec("user.plugins.telescope")
spec("user.plugins.nvimtree")
spec("user.plugins.comment")
spec("user.plugins.lualine")
spec("user.plugins.navic")
spec("user.plugins.breadcrumbs")
spec("user.plugins.illuminate")
spec("user.plugins.indentline")

-- extras
spec("user.plugins.extras.copilot")
spec("user.plugins.extras.harpoon")
-- spec("user.plugins.extras.neoscroll")
-- spec("user.plugins.extras.noice")
spec("user.plugins.extras.fold")
spec("user.plugins.extras.visual-multi")
spec("user.plugins.extras.surround")
spec("user.plugins.extras.rainbow")
spec("user.plugins.extras.lazygit")
spec("user.plugins.extras.eyeliner")
spec("user.plugins.extras.neotab")
-- lazy
require("user.lazy")
