#!/usr/bin/env bash

# Hardcoded config paths
configs=(
"$HOME/.bashrc"
"$DOTFILESDIR/i3/.config/i3/config"
"$DOTFILESDIR/nvim/.config/nvim/lua/user/init.lua"
"$DOTFILESDIR/zsh/.zshrc"
"$DOTFILESDIR/zsh/.zshenv"
"$DOTFILESDIR/zsh/.zsh_aliases"
"$DOTFILESDIR/zsh/.zsh_exports"
"$DOTFILESDIR/zsh/.zsh_functions"
"$DOTFILESDIR/zsh/.zsh_plugins"
"$DOTFILESDIR/polybar/.config/polybar/config.ini"
"$DOTFILESDIR/starship/starship.toml"
"$DOTFILESDIR/tmux/.tmux.conf"
"$DOTFILESDIR/picom/.config/picom.conf"
"$DOTFILESDIR/scripts/.scripts/my-config-selector"
"$DOTFILESDIR/install"
# ... (add more config paths as needed)
)

# Displaying options in fzf and getting the selection
choice=$(printf '%s\n' "${configs[@]}" | fzf --prompt 'Edit config: ')
# Check if an option was selected
if [ "$choice" ]; then
    # Extract the directory path from the selected file path
    dir_path=$(dirname "$choice")

    # Change to the directory containing the config file
    cd "$dir_path" || exit 1

    # Open the configuration file in Neovim
    nvim "$(basename "$choice")"
else
    echo "No selection made."
    exit 0
fi
