#!/usr/bin/env bash

# Define an array of folder prefixes
folder_prefixes=("project-" "BASE-" "MS-" "VFX-")

# Convert the array into a find-compatible expression
find_expr=""
for prefix in "${folder_prefixes[@]}"; do
    if [ -z "$find_expr" ]; then
        find_expr="-name \"$prefix*\""
    else
        find_expr="$find_expr -o -name \"$prefix*\""
    fi
done

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Combine all directories and subdirectories based on the specified prefixes
    selected=$(find ~/work ~/personal ~/dev ~/work_remote \
                $(eval find ~/work_remote -mindepth 1 -maxdepth 1 -type d \( $find_expr \)) \
                -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [[ -z $TMUX ]] && [[ -z $(pgrep tmux) ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    tmux switch-client -t $selected_name
fi


tmux switch-client -t $selected_name
