#!/bin/bash

# Check if the required positional argument is provided
if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g., 'the wonderful thing about tiggers'."
  exit 1
fi
if [ -z "$OBSIDIAN_VAULT_PATH" ]; then
  echo "Error: OBSIDIAN_VAULT_PATH is not set. Please set this environment variable to your Obsidian Vault directory path."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md

cd "${OBSIDIAN_VAULT_PATH}" || exit

mkdir -p inbox && touch "inbox/${formatted_file_name}"
nvim "inbox/${formatted_file_name}"
